# Enrollment Model

## Overview

The Enrollment model represents a student's registration in a specific course, tracking their progress and completion status.

## Schema

```typescript
interface Enrollment {
  id?: number;
  user_id: number;
  course_id: number;
  created_at?: Date;
  updated_at?: Date;
}
```

## Database Table

```sql
CREATE TABLE IF NOT EXISTS enrollments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  course_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
  UNIQUE KEY user_course (user_id, course_id)
);
```

## Methods

- `createEnrollment`: Creates a new enrollment record for a student in a course.
- `getEnrollmentById`: Retrieves an enrollment record by its ID.
- `isUserEnrolled`: Checks if a specific user is enrolled in a particular course.
- `getUserEnrollments`: Gets all courses a student is enrolled in.
- `getStudentEnrollments`: Gets a paginated and filtered list of a student's enrollments.
- `getCourseEnrollments`: Gets all students enrolled in a specific course.
- `getCourseRevenue`: Calculates the total revenue generated by a course.
- `getStudentCountByInstructor`: Gets the number of unique students enrolled in an instructor's courses.
- `getMostPopularCourses`: Retrieves courses sorted by enrollment count.
